DROP TABLE IF EXISTS Comments;
DROP TABLE IF EXISTS Item;
DROP TABLE IF EXISTS InterestList;
DROP TABLE IF EXISTS Notice;
DROP TABLE IF EXISTS Review;
DROP TABLE IF EXISTS Store;
DROP TABLE IF EXISTS Seller;
DROP TABLE IF EXISTS Event;
DROP TABLE IF EXISTS Admin;
DROP TABLE IF EXISTS BlackMember;
DROP TABLE IF EXISTS Login;
DROP TABLE IF EXISTS Member;
DROP TABLE IF EXISTS Industry;

DROP TRIGGER IF EXISTS MemberInsert;